# Generated by Django 5.2.7 on 2025-10-23 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0002_alter_organizer_profile_picture_and_more'),
        ('Event', '0002_remove_event_currency_remove_event_price_event_fee_and_more'),
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notification', to='Event.event'),
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ManyToManyField(related_name='user_tujuan', to='Authenticate.participant'),
        ),
    ]
