# Generated by Django 5.2.7 on 2025-10-25 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedNotifications',
            fields=[
                ('notifications_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Notification.notifications')),
                ('event_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            bases=('Notification.notifications',),
        ),
    ]
