# Generated by Django 5.2.7 on 2025-10-23 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0003_alter_organizer_contact_phone'),
        ('Event', '0002_remove_event_currency_remove_event_price_event_fee_and_more'),
        ('Notification', '0002_alter_notifications_event_remove_notifications_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_tujuan', to='Event.event'),
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tujuan', to='Authenticate.participant'),
        ),
    ]
