# Generated by Django 5.2.7 on 2025-10-25 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_alter_event_id'),
        ('Notification', '0002_deletednotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='event',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Event.event'),
        ),
    ]
