# Generated by Django 5.2.7 on 2025-10-24 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0003_alter_organizer_contact_phone'),
        ('Event', '0003_alter_event_id'),
        ('Notification', '0003_alter_notifications_event_remove_notifications_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tujuan', to='Event.event'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tujuan', to='Authenticate.participant'),
        ),
    ]
