# Generated by Django 5.2.7 on 2025-10-26 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0003_alter_notifications_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeletedNotifications',
        ),
    ]
