# Generated by Django 5.2.7 on 2025-10-24 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0004_alter_notifications_event_alter_notifications_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='event',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='timestamp',
        ),
    ]
