# Generated by Django 5.2.7 on 2025-10-24 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_alter_event_id'),
        ('Notification', '0005_remove_notifications_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.AddField(
            model_name='notifications',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_tujuan', to='Event.event'),
        ),
    ]
