# Generated by Django 5.2.7 on 2025-10-24 07:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0003_alter_organizer_contact_phone'),
        ('Event', '0003_alter_event_id'),
        ('Notification', '0006_remove_notifications_user_notifications_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ManyToManyField(related_name='user_tujuan', to='Authenticate.participant'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_tujuan', to='Event.event'),
        ),
    ]
