# Generated by Django 5.2.7 on 2025-10-24 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0003_alter_organizer_contact_phone'),
        ('Notification', '0008_alter_notifications_event_alter_notifications_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='user',
        ),
        migrations.AddField(
            model_name='notifications',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tujuan', to='Authenticate.participant'),
        ),
    ]
