# Generated by Django 5.2.7 on 2025-10-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0009_remove_notifications_user_notifications_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='is_read',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
