# Generated by Django 5.2.7 on 2025-10-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0010_alter_notifications_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
