# Generated by Django 5.2.7 on 2025-10-24 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0003_alter_event_id'),
        ('Notification', '0011_alter_notifications_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='event_temp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_tujuan_temp', to='Event.event'),
        ),
    ]
