# Generated by Django 5.2.7 on 2025-11-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmark', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
