# Generated by Django 5.2.7 on 2025-10-23 15:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmark', '0001_initial'),
        ('Event', '0002_remove_event_currency_remove_event_price_event_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'event')},
        ),
    ]
