# Generated by Django 5.2.7 on 2025-11-23 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bookmark', '0002_bookmark_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='note',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
