# Generated by Django 5.2.7 on 2025-10-23 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authenticate', '0002_alter_organizer_profile_picture_and_more'),
        ('Event', '0002_remove_event_currency_remove_event_price_event_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='Event.event')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='Forum.forumpost')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='Authenticate.participant')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
