# Generated by Django 5.2.7 on 2025-10-26 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0001_initial'),
        ('Forum', '0002_forumpost_organizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Authenticate.participant'),
        ),
    ]
