# Generated by Django 5.2.7 on 2025-10-26 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0001_initial'),
        ('Event', '0001_initial'),
        ('Forum', '0003_alter_forumpost_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='organizer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to='Authenticate.organizer'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='participant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts', to='Authenticate.participant'),
        ),
    ]
