# Generated by Django 5.2.7 on 2025-10-26 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_alter_forumpost_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumpost',
            old_name='profile',
            new_name='participant',
        ),
    ]
