# Generated by Django 5.2.7 on 2025-12-21 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_in_dashboard', to='Event.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_pins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'created_at'],
                'indexes': [models.Index(fields=['user', 'position'], name='Dashboard_p_user_id_2cf329_idx'), models.Index(fields=['user', 'event'], name='Dashboard_p_user_id_4bdf43_idx')],
                'unique_together': {('user', 'event')},
            },
        ),
    ]
