# Generated by Django 5.2.7 on 2025-10-22 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True, null=True)),
                ('sports_category', models.CharField(choices=[('running', 'Running'), ('padel', 'Padel'), ('football', 'Football'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('badminton', 'Badminton'), ('fitness', 'Fitness'), ('cycling', 'Cycling'), ('poundfit', 'Poundfit')], max_length=20)),
                ('activity_category', models.CharField(choices=[('fun_run_ride', 'Fun Run/Ride'), ('marathon', 'Marathon'), ('friendly_match', 'Friendly Match'), ('course', 'Course'), ('tournament', 'Tournament'), ('open_play', 'Open Play'), ('workshop', 'Workshop')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(blank=True, default='IDR', max_length=3, null=True)),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
