# Generated by Django 5.2.7 on 2025-10-26 07:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authenticate', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=120)),
                ('address', models.TextField(blank=True, null=True)),
                ('sports_category', models.CharField(choices=[('running', 'Running'), ('padel', 'Padel'), ('football', 'Football'), ('yoga', 'Yoga'), ('pilates', 'Pilates'), ('badminton', 'Badminton'), ('fitness', 'Fitness'), ('cycling', 'Cycling'), ('poundfit', 'Poundfit')], max_length=20)),
                ('activity_category', models.CharField(choices=[('fun_run_ride', 'Fun Run/Ride'), ('marathon', 'Marathon'), ('friendly_match', 'Friendly Match'), ('course', 'Course'), ('tournament', 'Tournament'), ('open_play', 'Open Play'), ('workshop', 'Workshop')], max_length=20)),
                ('fee', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('attendee', models.ManyToManyField(blank=True, related_name='events_joined', to='Authenticate.participant')),
                ('organizer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_events', to='Authenticate.organizer')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
