# Generated by Django 5.2.7 on 2025-10-23 06:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0001_initial'),
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='event',
            name='price',
        ),
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='event',
            name='attendee',
            field=models.ManyToManyField(blank=True, related_name='events_joined', to='Authenticate.participant'),
        ),
    ]
