# Generated by Django 5.2.7 on 2025-10-26 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.event')),
            ],
        ),
    ]
