# Generated by Django 5.2.7 on 2025-10-23 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
        ('Homepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardevent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='cardevent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='cardevent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='cardevent',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cardevent',
            name='location',
        ),
        migrations.RemoveField(
            model_name='cardevent',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cardevent',
            name='price',
        ),
        migrations.AddField(
            model_name='cardevent',
            name='parent_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Event.event'),
        ),
    ]
