# Generated by Django 5.2.7 on 2025-10-23 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authenticate', '0002_alter_organizer_profile_picture_and_more'),
        ('Event', '0002_remove_event_currency_remove_event_price_event_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Buruk'), (2, '2 - Kurang'), (3, '3 - Cukup'), (4, '4 - Baik'), (5, '5 - Sangat Baik')], default=5)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Event.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Authenticate.participant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('event', 'participant')},
            },
        ),
    ]
