# Generated by Django 5.2.7 on 2025-10-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='bio',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='bio',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='age',
            new_name='birth_date',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='location',
        ),
        migrations.AlterField(
            model_name='organizer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
