# Generated by Django 5.2.7 on 2025-10-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0002_alter_organizer_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
